services:
  open-webui:
    image: "ghcr.io/open-webui/open-webui:main"
    container_name: "open-webui"
    ports:
      - "8080:8080"
    environment:
      - OPENAI_API_BASE=http://host.docker.internal:1234/v1
      - OPENAI_API_NAMES=LM Studio
      - OLLAMA_BASE_URL=http://host.docker.internal:11434
      - ENABLE_RAG_WEB_SEARCH=True
      - RAG_WEB_SEARCH_ENGINE=searxng
      - RAG_WEB_SEARCH_RESULT_COUNT=3
      - RAG_WEB_SEARCH_CONCURRENT_REQUESTS=10
      - SEARXNG_QUERY_URL=http://searxng:8080/search?q=<query>
    volumes:
      - ./open-webui:/app/backend/data
    restart: unless-stopped

  searxng:
    image: "searxng/searxng:latest"
    container_name: "searxng"
    volumes:
      - ./searxng:/etc/searxng:rw
    restart: unless-stopped
    ports:
      - "8888:8080"  # Maps host port 8888 to container port 8080
    environment:
      - SEARXNG_BIND_ADDRESS=0.0.0.0
      - SEARXNG_PORT=8080
